# Generated by Django 5.1.2 on 2025-11-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessapp',
            options={},
        ),
        migrations.RemoveField(
            model_name='businessapp',
            name='a',
        ),
        migrations.RemoveField(
            model_name='businessapp',
            name='b',
        ),
        migrations.RemoveField(
            model_name='businessapp',
            name='c',
        ),
        migrations.RemoveField(
            model_name='businessapp',
            name='result',
        ),
        migrations.RemoveField(
            model_name='businessapp',
            name='student',
        ),
        migrations.RemoveField(
            model_name='businessapp',
            name='task',
        ),
        migrations.AddField(
            model_name='businessapp',
            name='r_amount',
            field=models.IntegerField(default=0, verbose_name='Количество ресурса'),
        ),
        migrations.AddField(
            model_name='businessapp',
            name='r_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название ресурса'),
        ),
        migrations.AddField(
            model_name='businessapp',
            name='r_price',
            field=models.IntegerField(default=0, verbose_name='цена ресурса'),
        ),
        migrations.AddField(
            model_name='businessapp',
            name='s_amount',
            field=models.IntegerField(default=0, verbose_name='Количество ресурса'),
        ),
        migrations.AddField(
            model_name='businessapp',
            name='s_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название ресурса'),
        ),
        migrations.AddField(
            model_name='businessapp',
            name='s_price',
            field=models.IntegerField(default=0, verbose_name='цена ресурса'),
        ),
    ]
