# Generated by Django 5.1.2 on 2025-11-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0002_alter_businessapp_options_remove_businessapp_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessapp',
            options={'ordering': ('id',), 'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблицы'},
        ),
    ]
