# Generated by Django 5.1.2 on 2025-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0003_alter_businessapp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapp',
            name='r_price',
            field=models.IntegerField(default=0, verbose_name='Цена ресурса'),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='s_amount',
            field=models.IntegerField(default=0, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='s_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='s_price',
            field=models.IntegerField(default=0, verbose_name='Цена товара'),
        ),
    ]
