# Generated by Django 5.1.2 on 2025-11-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0004_alter_businessapp_r_price_alter_businessapp_s_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapp',
            name='r_name',
            field=models.CharField(default='отсутствует', max_length=255, verbose_name='Название ресурса'),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='r_price',
            field=models.FloatField(default=0, verbose_name='Цена ресурса'),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='s_name',
            field=models.CharField(default='отсутствует', max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='s_price',
            field=models.FloatField(default=0, verbose_name='Цена товара'),
        ),
    ]
