# Generated by Django 5.1.2 on 2025-11-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0005_alter_businessapp_r_name_alter_businessapp_r_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapp',
            name='current_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения (save)'),
        ),
    ]
