# Generated by Django 5.1.2 on 2025-11-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0006_alter_businessapp_current_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessapp',
            options={'ordering': ('id',), 'verbose_name': 'Запись', 'verbose_name_plural': 'Таблицы'},
        ),
    ]
