# Generated by Django 5.1.2 on 2024-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcmodel',
            name='student',
            field=models.CharField(default='Иванов', max_length=255, verbose_name='Фамилия студента'),
        ),
    ]
