# Generated by Django 4.0.4 on 2025-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0002_abcmodel_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcmodel',
            options={'ordering': ('student',), 'verbose_name': 'A_B_C_Таблица', 'verbose_name_plural': 'A_B_C_Таблицы'},
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='a',
            field=models.IntegerField(default=2, help_text='Подсказка для значения А', verbose_name='Значение А'),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='b',
            field=models.IntegerField(default=3, help_text='Подсказка для значения B', verbose_name='Значение B'),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='result',
            field=models.CharField(default='Результат не определен', max_length=255),
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='task',
            field=models.CharField(default='Равна ли С сумме A и B ??', max_length=255, verbose_name='Формулировка  задачи'),
        ),
    ]
